name: easybook
"on":
    push:
        branches:
            - main
    workflow_dispatch: {}
env:
    ACR_RESOURCE_GROUP: easyabpregistry
    AZURE_CONTAINER_REGISTRY: easyabpregistry
    CLUSTER_NAME: easyabp
    CLUSTER_RESOURCE_GROUP: aks
    CONTAINER_NAME: bookflashsales
    DEPLOYMENT_MANIFEST_PATH: |
        ./bookflashsales.yaml
jobs:
    buildImage:
        permissions:
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: azure/login@v1.4.3
              name: Azure login
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            - name: Build and push image to ACR
              run: az acr build --image ${{ env.CONTAINER_NAME }}:latest --registry ${{ env.AZURE_CONTAINER_REGISTRY }} -g ${{ env.ACR_RESOURCE_GROUP }} -f ./src/BookFlashSales.Web/Dockerfile ./
#               run: az acr build --image ${{ env.CONTAINER_NAME }}:${{ github.sha }} --registry ${{ env.AZURE_CONTAINER_REGISTRY }} -g ${{ env.ACR_RESOURCE_GROUP }} -f ./src/BookFlashSales.Web/Dockerfile ./
    deploy:
        permissions:
            actions: read
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        needs:
            - buildImage
        steps:
            - uses: actions/checkout@v3
            - uses: azure/login@v1.4.3
              name: Azure login
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            - uses: azure/aks-set-context@v3
              name: Get K8s context
              with:
                cluster-name: ${{ env.CLUSTER_NAME }}
                resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
            #- name: ls
              #run: sed -i '0,/Default[^,]*/s//${{ github.sha }}/g' bookflashsales.yaml
              #run: sed 's/Default/${{ github.sha }}/g' ${{ env.DEPLOYMENT_MANIFEST_PATH }}
            - uses: Azure/k8s-deploy@v4
              name: Deploys application
              with:
                action: deploy
#                 images: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }}
                run: sed 's/Default/${{ github.sha }}/g' /tmp/bookflashsales.yaml
                images: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:latest 
                manifests: ${{ env.DEPLOYMENT_MANIFEST_PATH }}
                namespace: easyabp
